# Generated by Django 4.2.7 on 2026-06-03 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "customer_code",
                    models.CharField(max_length=50, unique=True, verbose_name="客户编码"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="客户名称")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=80, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="电话"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "customer_type",
                    models.CharField(
                        default="buyer", max_length=40, verbose_name="客户类型"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=0, verbose_name="客户等级"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="信用额度"
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="当前余额"
                    ),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "ordering": ["customer_code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document_no",
                    models.CharField(max_length=120, unique=True, verbose_name="库存单号"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("stock_in", "入库"),
                            ("stock_out", "出库"),
                            ("return", "退货"),
                            ("transfer", "调拨"),
                            ("opening_balance", "期初"),
                        ],
                        max_length=30,
                        verbose_name="单据类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("posted", "已过账"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("business_time", models.DateTimeField(verbose_name="业务时间")),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过账时间"),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=80, verbose_name="来源类型"),
                ),
                (
                    "source_ref",
                    models.CharField(blank=True, max_length=120, verbose_name="来源单号"),
                ),
                ("memo", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存单据",
                "verbose_name_plural": "库存单据",
                "ordering": ["-business_time", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(verbose_name="行号")),
                (
                    "quantity_bucket",
                    models.CharField(
                        default="on_hand", max_length=40, verbose_name="库存桶"
                    ),
                ),
                (
                    "delta_quantity",
                    models.BigIntegerField(default=0, verbose_name="变动数量"),
                ),
                (
                    "target_quantity",
                    models.BigIntegerField(blank=True, null=True, verbose_name="目标数量"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="单位成本",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存单据明细",
                "verbose_name_plural": "库存单据明细",
                "ordering": ["document_id", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "metric_code",
                    models.CharField(max_length=100, unique=True, verbose_name="指标编码"),
                ),
                ("metric_name", models.CharField(max_length=120, verbose_name="指标名称")),
                ("metric_domain", models.CharField(max_length=80, verbose_name="指标域")),
                ("grain", models.CharField(max_length=100, verbose_name="统计粒度")),
                ("source_fact", models.CharField(max_length=120, verbose_name="来源事实")),
                (
                    "owner",
                    models.CharField(blank=True, max_length=100, verbose_name="负责人"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="状态"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
            ],
            options={
                "verbose_name": "指标定义",
                "verbose_name_plural": "指标定义",
                "ordering": ["metric_code"],
            },
        ),
        migrations.CreateModel(
            name="OperationTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(max_length=80, unique=True, verbose_name="运营组编码"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="运营组名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "运营组",
                "verbose_name_plural": "运营组",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="货号"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="商品名称")),
                (
                    "specification",
                    models.CharField(blank=True, max_length=255, verbose_name="规格"),
                ),
                (
                    "unit",
                    models.CharField(default="件", max_length=100, verbose_name="单位"),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=100, verbose_name="条码"),
                ),
                (
                    "brand",
                    models.CharField(default="外贸通", max_length=80, verbose_name="品牌"),
                ),
                (
                    "year",
                    models.CharField(blank=True, max_length=10, verbose_name="年份"),
                ),
                (
                    "season",
                    models.CharField(blank=True, max_length=20, verbose_name="季节"),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=100, verbose_name="分类"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="颜色"),
                ),
                (
                    "safety_stock",
                    models.IntegerField(blank=True, null=True, verbose_name="安全库存"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(blank=True, default=dict, verbose_name="自定义字段"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("variant_key", models.CharField(max_length=160, verbose_name="变体键")),
                (
                    "sku_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=50, verbose_name="尺码"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="颜色"),
                ),
                (
                    "specification",
                    models.CharField(blank=True, max_length=255, verbose_name="规格"),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=100, verbose_name="条码"),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="默认变体")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="operations.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品变体",
                "verbose_name_plural": "商品变体",
                "ordering": ["product_id", "variant_key"],
                "unique_together": {("product", "variant_key")},
            },
        ),
        migrations.CreateModel(
            name="ReportQueryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "query_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="查询模型编码"
                    ),
                ),
                ("query_name", models.CharField(max_length=120, verbose_name="查询模型名称")),
                ("report_domain", models.CharField(max_length=80, verbose_name="报表域")),
                ("source_fact", models.CharField(max_length=120, verbose_name="主事实源")),
                (
                    "default_time_field",
                    models.CharField(max_length=100, verbose_name="默认时间字段"),
                ),
                (
                    "default_grain",
                    models.CharField(max_length=100, verbose_name="默认粒度"),
                ),
                (
                    "permission_code",
                    models.CharField(blank=True, max_length=100, verbose_name="权限编码"),
                ),
                (
                    "cache_policy",
                    models.CharField(
                        default="none", max_length=30, verbose_name="缓存策略"
                    ),
                ),
                (
                    "default_params",
                    models.JSONField(blank=True, default=dict, verbose_name="默认参数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表查询模型",
                "verbose_name_plural": "报表查询模型",
                "ordering": ["query_code"],
            },
        ),
        migrations.CreateModel(
            name="SalesDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document_no",
                    models.CharField(max_length=120, unique=True, verbose_name="销售单号"),
                ),
                (
                    "document_type",
                    models.CharField(
                        default="sale", max_length=30, verbose_name="单据类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("posted", "已过账"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "customer_name_snapshot",
                    models.CharField(blank=True, max_length=255, verbose_name="客户快照"),
                ),
                (
                    "transaction_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="交易时间"),
                ),
                (
                    "source_system",
                    models.CharField(blank=True, max_length=80, verbose_name="来源系统"),
                ),
                (
                    "source_record_key",
                    models.CharField(blank=True, max_length=255, verbose_name="来源记录"),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="币种"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="总金额"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售单据",
                "verbose_name_plural": "销售单据",
                "ordering": ["-transaction_time", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalesDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(verbose_name="行号")),
                (
                    "product_code_snapshot",
                    models.CharField(max_length=100, verbose_name="货号快照"),
                ),
                (
                    "sku_key_snapshot",
                    models.CharField(blank=True, max_length=160, verbose_name="SKU 快照"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="金额"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="operations.salesdocument",
                        verbose_name="销售单据",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.productvariant",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售单据明细",
                "verbose_name_plural": "销售单据明细",
                "ordering": ["document_id", "line_no"],
                "unique_together": {("document", "line_no")},
            },
        ),
        migrations.CreateModel(
            name="SalesPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(max_length=80, unique=True, verbose_name="平台编码"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="平台名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "销售平台",
                "verbose_name_plural": "销售平台",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="店铺名称"),
                ),
                (
                    "shop_url",
                    models.URLField(blank=True, max_length=500, verbose_name="店铺地址"),
                ),
                (
                    "owner",
                    models.CharField(blank=True, max_length=80, verbose_name="负责人"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=30, verbose_name="联系电话"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "sales_type",
                    models.CharField(
                        choices=[("retail", "零售"), ("wholesale", "批发")],
                        default="retail",
                        max_length=20,
                        verbose_name="销售类型",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.salesplatform",
                        verbose_name="销售平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "supplier_code",
                    models.CharField(max_length=80, unique=True, verbose_name="供应商编码"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="供应商名称")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=80, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="电话"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
                "ordering": ["supplier_code"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="仓库编码",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仓库名称")),
                (
                    "warehouse_kind",
                    models.CharField(
                        default="standard", max_length=20, verbose_name="仓库类型"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "manager",
                    models.CharField(blank=True, max_length=120, verbose_name="负责人"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="SalesLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        default="sale", max_length=30, verbose_name="流水类型"
                    ),
                ),
                (
                    "quantity_scope",
                    models.CharField(
                        default="deal", max_length=30, verbose_name="数量口径"
                    ),
                ),
                (
                    "entry_status",
                    models.CharField(
                        default="posted", max_length=20, verbose_name="流水状态"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="数量"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="金额"
                    ),
                ),
                ("business_time", models.DateTimeField(verbose_name="业务时间")),
                (
                    "idempotency_key",
                    models.CharField(max_length=255, unique=True, verbose_name="幂等键"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.salesdocument",
                        verbose_name="销售单据",
                    ),
                ),
                (
                    "document_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.salesdocumentline",
                        verbose_name="销售明细",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.shop",
                        verbose_name="店铺",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.productvariant",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售流水",
                "verbose_name_plural": "销售流水",
                "ordering": ["-business_time"],
            },
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operations.shop",
                verbose_name="店铺",
            ),
        ),
        migrations.CreateModel(
            name="ReportQuerySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(blank=True, default=dict, verbose_name="查询参数"),
                ),
                (
                    "result",
                    models.JSONField(blank=True, default=list, verbose_name="结果"),
                ),
                (
                    "metric_versions",
                    models.JSONField(blank=True, default=list, verbose_name="指标版本"),
                ),
                (
                    "source_trace",
                    models.JSONField(blank=True, default=dict, verbose_name="来源追踪"),
                ),
                (
                    "data_mode",
                    models.CharField(
                        default="realtime", max_length=30, verbose_name="数据模式"
                    ),
                ),
                ("snapshot_time", models.DateTimeField(verbose_name="快照时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "query_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="operations.reportquerymodel",
                        verbose_name="查询模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表查询快照",
                "verbose_name_plural": "报表查询快照",
                "ordering": ["-snapshot_time"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order_no",
                    models.CharField(max_length=120, unique=True, verbose_name="采购单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("approved", "已审核"),
                            ("in_transit", "在途"),
                            ("received", "已入库"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="下单日期")),
                (
                    "expected_arrival_date",
                    models.DateField(blank=True, null=True, verbose_name="预计到货日期"),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="入库时间"),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="币种"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="总金额"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.shop",
                        verbose_name="关联店铺",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.warehouse",
                        verbose_name="入库仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购订单",
                "verbose_name_plural": "采购订单",
                "ordering": ["-order_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLedger",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="流水事件ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=32, verbose_name="事件类型")),
                (
                    "delta_quantity",
                    models.BigIntegerField(default=0, verbose_name="变动数量"),
                ),
                (
                    "snapshot_quantity",
                    models.BigIntegerField(blank=True, null=True, verbose_name="变动后数量"),
                ),
                ("biz_time", models.DateTimeField(verbose_name="业务时间")),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=64, verbose_name="来源类型"),
                ),
                (
                    "source_ref",
                    models.CharField(blank=True, max_length=128, verbose_name="来源单号"),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=128, unique=True, verbose_name="幂等键"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.inventorydocumentline",
                        verbose_name="库存单据行",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.productvariant",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存流水",
                "verbose_name_plural": "库存流水",
                "ordering": ["-biz_time"],
            },
        ),
        migrations.AddField(
            model_name="inventorydocumentline",
            name="counterpart_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counterpart_inventory_lines",
                to="operations.warehouse",
                verbose_name="对方仓库",
            ),
        ),
        migrations.AddField(
            model_name="inventorydocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="operations.inventorydocument",
                verbose_name="库存单据",
            ),
        ),
        migrations.AddField(
            model_name="inventorydocumentline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="operations.product",
                verbose_name="商品",
            ),
        ),
        migrations.AddField(
            model_name="inventorydocumentline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="operations.productvariant",
                verbose_name="SKU",
            ),
        ),
        migrations.AddField(
            model_name="inventorydocumentline",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_lines",
                to="operations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.CreateModel(
            name="ShopAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignment_role",
                    models.CharField(
                        default="owner", max_length=30, verbose_name="分工角色"
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(auto_now_add=True, verbose_name="生效时间"),
                ),
                (
                    "effective_to",
                    models.DateTimeField(blank=True, null=True, verbose_name="失效时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "operation_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.operationteam",
                        verbose_name="运营组",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="operations.shop",
                        verbose_name="店铺",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺分配",
                "verbose_name_plural": "店铺分配",
                "unique_together": {
                    ("shop", "operation_team", "user", "assignment_role")
                },
            },
        ),
        migrations.CreateModel(
            name="ReportQueryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.CharField(max_length=100, verbose_name="字段键")),
                ("field_label", models.CharField(max_length=120, verbose_name="字段名")),
                ("field_role", models.CharField(max_length=20, verbose_name="字段角色")),
                (
                    "data_type",
                    models.CharField(
                        default="string", max_length=30, verbose_name="数据类型"
                    ),
                ),
                ("expression_text", models.TextField(blank=True, verbose_name="表达式")),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必选"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="是否显示")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.metricdefinition",
                        verbose_name="指标",
                    ),
                ),
                (
                    "query_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="operations.reportquerymodel",
                        verbose_name="查询模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表查询字段",
                "verbose_name_plural": "报表查询字段",
                "ordering": ["query_model_id", "sort_order", "id"],
                "unique_together": {("query_model", "field_key")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(verbose_name="行号")),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="采购数量"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="已收数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="采购单价"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="金额"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="operations.purchaseorder",
                        verbose_name="采购订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.productvariant",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购订单明细",
                "verbose_name_plural": "采购订单明细",
                "ordering": ["order_id", "line_no"],
                "unique_together": {("order", "line_no")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="inventorydocumentline",
            unique_together={("document", "line_no")},
        ),
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("quantity", models.BigIntegerField(default=0, verbose_name="当前库存")),
                (
                    "last_biz_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后业务时间"),
                ),
                (
                    "last_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.inventoryledger",
                        verbose_name="最后流水",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.productvariant",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "当前库存余额",
                "verbose_name_plural": "当前库存余额",
                "unique_together": {("product", "variant", "warehouse")},
            },
        ),
    ]
