# Generated by Django 5.0.14 on 2026-06-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_salesdocument_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="属性编码"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="属性名称")),
                (
                    "data_type",
                    models.CharField(
                        default="string", max_length=30, verbose_name="数据类型"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "商品扩展属性定义",
                "verbose_name_plural": "商品扩展属性定义",
                "ordering": ["code"],
            },
        ),
        migrations.RemoveField(
            model_name="inventorydocumentline",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="inventoryledger",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="inventoryledger",
            name="snapshot_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="custom_fields",
        ),
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="reportquerymodel",
            name="default_params",
        ),
        migrations.RemoveField(
            model_name="salesdocument",
            name="customer_name_snapshot",
        ),
        migrations.RemoveField(
            model_name="salesdocumentline",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="salesdocumentline",
            name="product_code_snapshot",
        ),
        migrations.RemoveField(
            model_name="salesdocumentline",
            name="sku_key_snapshot",
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.CharField(max_length=255, verbose_name="属性值")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.productattributedefinition",
                        verbose_name="属性",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="operations.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品扩展属性值",
                "verbose_name_plural": "商品扩展属性值",
                "ordering": ["product_id", "attribute_id"],
                "unique_together": {("product", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="ReportQueryParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("param_key", models.CharField(max_length=100, verbose_name="参数键")),
                ("param_label", models.CharField(max_length=120, verbose_name="参数名")),
                (
                    "data_type",
                    models.CharField(
                        default="string", max_length=30, verbose_name="数据类型"
                    ),
                ),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, verbose_name="默认值"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必填"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "query_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="operations.reportquerymodel",
                        verbose_name="查询模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表查询参数",
                "verbose_name_plural": "报表查询参数",
                "ordering": ["query_model_id", "sort_order", "id"],
                "unique_together": {("query_model", "param_key")},
            },
        ),
        migrations.DeleteModel(
            name="ReportQuerySnapshot",
        ),
    ]
