# Generated by Django 5.0.14 on 2026-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="权限编码"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="权限名称")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "权限码",
                "verbose_name_plural": "权限码",
                "ordering": ["code"],
            },
        ),
        migrations.RemoveField(
            model_name="permissiongroup",
            name="permissions",
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="permission_groups",
                to="authentication.permissioncode",
                verbose_name="权限码",
            ),
        ),
    ]
